const fs = require('fs');
const PAGE = '/home/user/yoga-app/lumen-log-practice-3d.html';

const frontRaw = fs.readFileSync(__dirname + '/front2_markup.txt', 'utf8');
const backRaw  = fs.readFileSync(__dirname + '/back2_markup.txt', 'utf8');

// Both files start with the shared DEFS block; split it off.
const defsEnd = frontRaw.indexOf('</defs>') + '</defs>'.length;
const DEFS  = frontRaw.slice(0, defsEnd);
const FRONT = frontRaw.slice(defsEnd).trim();
const BACK  = backRaw.slice(backRaw.indexOf('</defs>') + '</defs>'.length).trim();

let html = fs.readFileSync(PAGE, 'utf8');

// ── 1. Replace getSVGMarkup() body ──
const fnStart = html.indexOf('function getSVGMarkup(view) {');
const fnEnd   = html.indexOf('function attachSvgHandlers()');
if (fnStart < 0 || fnEnd < 0) throw new Error('markers not found');

const newFn = `function getSVGMarkup(view) {
  // M3a anatomical illustration: crimson muscle material with per-muscle
  // volume gradient, silvery fascia/tendon layer, striation fibers along
  // each muscle's contraction axis, and specular rim ("chisel") lighting.
  // Generated by the bodymap toolkit (gen2.js/render.js) — do not hand-edit
  // paths; regenerate via build_front2.js / build_back2.js.
  const defs = \`${DEFS}\`;

  if (view === 'front') {
    return defs + \`
${FRONT}
    \`;
  } else {
    return defs + \`
${BACK}
    \`;
  }
}

`;
html = html.slice(0, fnStart) + newFn + html.slice(fnEnd);

// ── 2. CSS: new material rules ──
const oldCss = `#svg-body .svgm-bg{fill:url(#fg1)}
#svg-body .svgm{fill:url(#fg1);stroke:#5A2418;stroke-width:0.6;transition:fill .15s,filter .1s}
#svg-body .svgm:hover{filter:brightness(1.28)}
#svg-body .svgm.picking{filter:brightness(1.55) saturate(1.2)}`;
const newCss = `#svg-body .svgm-bg{fill:#3A1210}
#svg-body .svgm{fill:url(#muscleGrad);stroke:#2A0A0B;stroke-width:0.7;transition:fill .15s,filter .1s;filter:url(#chisel)}
#svg-body .svgm.svgm-t{fill:url(#fasciaGrad);stroke:#6E6A60}
#svg-body .svgm:hover{filter:url(#chisel) brightness(1.28)}
#svg-body .svgm.picking{filter:url(#chisel) brightness(1.55) saturate(1.2)}
#svg-body .svgm-fascia path{fill:url(#fasciaGrad);stroke:#6E6A60;stroke-width:0.3;opacity:0.85}
#svg-body .svgm-fibers path{fill:none;stroke:#1E0708;stroke-width:0.5;opacity:0.4}`;
if (!html.includes(oldCss)) throw new Error('CSS block not found');
html = html.replace(oldCss, newCss);

// ── 3. Feeling-clear fallback fill: tendon zones return to fascia paint ──
const oldFill = `el.style.fill = feeling && FEELINGS[feeling] ? FEELINGS[feeling].color : 'url(#fg1)';`;
const newFill = `el.style.fill = feeling && FEELINGS[feeling] ? FEELINGS[feeling].color
    : (el.classList.contains('svgm-t') ? 'url(#fasciaGrad)' : 'url(#muscleGrad)');`;
if (!html.includes(oldFill)) throw new Error('fill fallback not found');
html = html.replace(oldFill, newFill);

fs.writeFileSync(PAGE, html);
console.log('integrated: defs', DEFS.length, 'chars, front', FRONT.length, ', back', BACK.length);
